In [78]:
print('hello')

hello

In [85]:
import pandas as pd
df = pd.read_csv('./covid-data.csv')

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
43537,01/01/2021,OH,700380,628336.0,72044.0,0,0.0,8962,8112.0,850.0,0,0.0,01/02/2021 02:50:51 PM,Agree,Agree
28861,01/01/2021,VI,2036,NaN,NaN,0,0.0,23,NaN,NaN,0,0.0,01/02/2021 02:50:51 PM,NaN,NaN
6402,01/01/2021,NM,144142,NaN,NaN,1278,0.0,2409,NaN,NaN,24,1.0,01/03/2021 12:00:00 AM,NaN,Not agree
27979,01/01/2021,DE,59670,57252.0,2418.0,823,31.0,930,828.0,102.0,0,0.0,01/03/2021 12:00:00 AM,Agree,Agree
11009,01/01/2021,MD,280219,NaN,NaN,3557,0.0,6300,6110.0,190.0,43,0.0,01/03/2021 12:00:00 AM,NaN,Agree
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40410,12/31/2021,PW,12,NaN,NaN,0,0.0,0,NaN,NaN,0,0.0,01/01/2022 02:12:51 PM,NaN,NaN
8896,12/31/2021,OH,2016095,1589233.0,426862.0,20598,5021.0,29447,29447.0,0.0,667,0.0,01/01/2022 02:12:51 PM,Agree,Agree
12519,12/31/2021,GU,19618,NaN,NaN,11,0.0,270,NaN,NaN,0,0.0,01/01/2022 02:12:51 PM,Not agree,Not agree
7035,12/31/2021,IA,582348,NaN,NaN,6847,2004.0,7858,NaN,NaN,0,0.0,01/01/2022 02:12:51 PM,Not agree,Not agree
144,12/31/2021,MP,3255,3255.0,0.0,47,0.0,13,13.0,0.0,0,0.0,01/01/2022 02:12:51 PM,Agree,Agree

In [80]:
df['submission_date'] = pd.to_datetime(df['submission_date'])
df = df.sort_values(['state', 'submission_date'])
df

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
4532,2020-01-22,AK,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,03/26/2020 04:22:39 PM,NaN,NaN
357,2020-01-23,AK,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,03/26/2020 04:22:39 PM,NaN,NaN
2704,2020-01-24,AK,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,03/26/2020 04:22:39 PM,NaN,NaN
37706,2020-01-25,AK,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,03/26/2020 04:22:39 PM,NaN,NaN
5696,2020-01-26,AK,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,03/26/2020 04:22:39 PM,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33357,2022-01-21,WY,135369,106504.0,28865.0,1874,355.0,1601,1601.0,0.0,0,0.0,01/22/2022 02:22:36 PM,Agree,Agree
30931,2022-01-22,WY,135369,106504.0,28865.0,0,0.0,1601,1601.0,0.0,0,0.0,01/24/2022 02:28:34 PM,Agree,Agree
19540,2022-01-23,WY,135369,106504.0,28865.0,0,0.0,1601,1601.0,0.0,0,0.0,01/24/2022 03:59:16 PM,Agree,Agree
34296,2022-01-24,WY,137873,108554.0,29319.0,2504,454.0,1601,1601.0,0.0,0,0.0,01/25/2022 02:33:43 PM,Agree,Agree
30877,2022-01-25,WY,139461,109726.0,29735.0,1588,416.0,1625,1625.0,0.0,24,0.0,01/26/2022 03:12:02 PM,Agree,Agree

In [81]:
state = 'CA'

df_ca = df[df['state'] == state]

df_ca['tot_cases_diff'] = df_ca['tot_cases'].diff()
df_ca

C:\Users\sfitc\AppData\Local\Temp\ipykernel_60916\3690026505.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ca['tot_cases_diff'] = df_ca['tot_cases'].diff()

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths,tot_cases_diff
25559,2020-01-22,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/24/2020 12:00:00 AM,Agree,Not agree,NaN
12887,2020-01-23,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/25/2020 12:00:00 AM,Agree,Not agree,0.0
17546,2020-01-24,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/26/2020 12:00:00 AM,Agree,Not agree,0.0
15811,2020-01-25,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/27/2020 12:00:00 AM,Agree,Not agree,0.0
23711,2020-01-26,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/28/2020 12:00:00 AM,Agree,Not agree,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15277,2022-01-21,CA,7570538,7123571.0,446967.0,125861,0.0,77722,NaN,NaN,201,0.0,01/22/2022 02:22:36 PM,Agree,Not agree,125861.0
12157,2022-01-22,CA,7570538,7123571.0,446967.0,0,0.0,77722,NaN,NaN,0,0.0,01/24/2022 02:28:34 PM,Agree,Not agree,0.0
22672,2022-01-23,CA,7570538,7123571.0,446967.0,0,0.0,77722,NaN,NaN,0,0.0,01/24/2022 03:59:16 PM,Agree,Not agree,0.0
13594,2022-01-24,CA,7866610,7419643.0,446967.0,296072,0.0,78101,NaN,NaN,379,0.0,01/25/2022 02:33:43 PM,Agree,Not agree,296072.0
9524,2022-01-25,CA,7929436,7482469.0,446967.0,62826,0.0,78118,NaN,NaN,17,0.0,01/26/2022 03:12:02 PM,Agree,Not agree,62826.0

In [82]:
df_ca['tot_cases_diff'].mean()

10803.046321525886

In [83]:
df_ca['new_case_diff'] = df_ca.iloc['new_case'].diff()
print(df_ca['new_case_diff'].mean())
df_ca

85.59400544959128

C:\Users\sfitc\AppData\Local\Temp\ipykernel_60916\2858867613.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ca['new_case_diff'] = df_ca['new_case'].diff()

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths,tot_cases_diff,new_case_diff
25559,2020-01-22,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/24/2020 12:00:00 AM,Agree,Not agree,NaN,NaN
12887,2020-01-23,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/25/2020 12:00:00 AM,Agree,Not agree,0.0,0.0
17546,2020-01-24,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/26/2020 12:00:00 AM,Agree,Not agree,0.0,0.0
15811,2020-01-25,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/27/2020 12:00:00 AM,Agree,Not agree,0.0,0.0
23711,2020-01-26,CA,0,0.0,0.0,0,0.0,0,NaN,NaN,0,0.0,01/28/2020 12:00:00 AM,Agree,Not agree,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15277,2022-01-21,CA,7570538,7123571.0,446967.0,125861,0.0,77722,NaN,NaN,201,0.0,01/22/2022 02:22:36 PM,Agree,Not agree,125861.0,-34593.0
12157,2022-01-22,CA,7570538,7123571.0,446967.0,0,0.0,77722,NaN,NaN,0,0.0,01/24/2022 02:28:34 PM,Agree,Not agree,0.0,-125861.0
22672,2022-01-23,CA,7570538,7123571.0,446967.0,0,0.0,77722,NaN,NaN,0,0.0,01/24/2022 03:59:16 PM,Agree,Not agree,0.0,0.0
13594,2022-01-24,CA,7866610,7419643.0,446967.0,296072,0.0,78101,NaN,NaN,379,0.0,01/25/2022 02:33:43 PM,Agree,Not agree,296072.0,296072.0
9524,2022-01-25,CA,7929436,7482469.0,446967.0,62826,0.0,78118,NaN,NaN,17,0.0,01/26/2022 03:12:02 PM,Agree,Not agree,62826.0,-233246.0

In [84]:
mean_diff = df_ca['new_case_diff'].mean()

sentence = 'The average new weekly cases in {0} was {1} from {2} to {3}.'.format(
    state, 
    round(mean_diff, 2), 
    df_ca['submission_date'].iloc[0].date(), 
    df_ca['submission_date'].iloc[-1].date())

print(sentence)

The average new weekly cases in CA was 85.59 from 2020-01-22 to 2022-01-25.